/*[
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse,aspernatur.`,
  ];
  */
let myjoke = [
  {
    category: "Programming",
    type: "single",
    joke: "Being a self-taught developer is almost the same as being a cut neck chicken because you have no sense of direction in the beginning.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 184,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Debugging: Removing the needles from the haystack.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 40,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "How did you make your friend rage?",
    delivery: "I implemented a greek question mark in his JavaScript code.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 147,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'Judge: "I sentence you to the maximum punishment..."\nMe (thinking): "Please be death, please be death..."\nJudge: "Learn Java!"\nMe: "Damn."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 45,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "What is a dying programmer's last program?",
    delivery: "Goodbye, world!",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 56,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "How do you know God is a shitty programmer?",
    delivery:
      "He wrote the OS for an entire universe, but didn't leave a single useful comment.",
    flags: {
      nsfw: false,
      religious: true,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    id: 19,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "A programmer puts two glasses on his bedside table before going to sleep.\nA full one, in case he gets thirsty, and an empty one, in case he doesn't.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 3,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "Why are modern programming languages so materialistic?",
    delivery: "Because they are object-oriented.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 21,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "What are bits?",
    delivery: "Tiny things left when you drop your computer down the stairs.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 211,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: ".NET developers are picky when it comes to food.",
    delivery: "They only like chicken NuGet.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 49,
    safe: true,
    lang: "en",
  },
  {
    category: "Dark",
    type: "single",
    joke: "Hey girl are you a school? Because I want to shoot some kids up inside of you.",
    flags: {
      nsfw: true,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    safe: false,
    id: 269,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: "I'm reading a book about anti-gravity. It's impossible to put down!",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 126,
    safe: true,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: 'Today, my son asked "Can I have a book mark?" and I burst into tears.\n11 years old and he still doesn\'t know my name is Brian.',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 200,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "A programmer puts two glasses on his bedside table before going to sleep.\nA full one, in case he gets thirsty, and an empty one, in case he doesn't.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 3,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Have a great weekend!\nI hope your code behaves the same on Monday as it did on Friday.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 44,
    safe: true,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "Women are like KFC, once you're done with the breasts and thighs, you just have a greasy box to put your bone in.",
    flags: {
      nsfw: true,
      religious: false,
      political: false,
      racist: false,
      sexist: true,
      explicit: true,
    },
    id: 149,
    safe: false,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: "Oysters hate to give away their pearls because they are shellfish.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 90,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Documentation is like sex:\nWhen it's good, it's very good.\nWhen it's bad, it's better than nothing...",
    flags: {
      nsfw: true,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: false,
    id: 305,
    lang: "en",
  },
  {
    category: "Dark",
    type: "single",
    joke: 'Doctor: "I have some news about your baby."\nParents: "Don\'t tell us the gender, we want to keep it a surprise."\nDoctor: "Oh I get it, you\'re those type of people. Okay, well IT is not breathing."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 138,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'Four engineers get into a car. The car won\'t start.\nThe Mechanical engineer says "It\'s a broken starter".\nThe Electrical engineer says "Dead battery".\nThe Chemical engineer says "Impurities in the gasoline".\nThe IT engineer says "Hey guys, I have an idea: How about we all get out of the car and get back in".',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 132,
    safe: true,
    lang: "en",
  },
];

let index = Math.floor(Math.random() * (myjoke.length - 1));
// const joke=innerHtml
console.log(index);
joke.innerHTML = myjoke[index].joke;

// const j = document.getElementById("joke");
// const j2 = j.innerHtml;
// myjoke[index].j2;
// j.innerHtml = myjoke[index];
